### ISSUE TITLE
[Bug]: Cannot find module '@stackpath/node-grpc-error-details'

### ISSUE THREAD

**Issue by happy-turtle** [inworld-ai/inworld-nodejs-sdk#167]
### Version

1.14.0

## Steps to reproduce the problem
1. Update @inworld/nodejs-sdk to 1.14.0 in package.json
2. Run `bun install`
3. Run Nuxt.JS development server with `bun run dev`

## What happened?
```
 ERROR  [worker reload] [worker init] Cannot find module '@stackpath/node-grpc-error-details'
Require stack:
- node_modules\@inworld\nodejs-sdk\build\src\entities\error.entity.js
- node_modules\@inworld\nodejs-sdk\build\src\services\gprc\world_engine_client_grpc.service.js   
- node_modules\@inworld\nodejs-sdk\build\src\services\connection.service.js
- node_modules\@inworld\nodejs-sdk\build\src\clients\inworld.client.js
- node_modules\@inworld\nodejs-sdk\build\src\index.js
webview:dev:
  Require stack:
  - node_modules\@inworld\nodejs-sdk\build\src\entities\error.entity.js
  - node_modules\@inworld\nodejs-sdk\build\src\services\gprc\world_engine_client_grpc.service.js 
  - node_modules\@inworld\nodejs-sdk\build\src\services\connection.service.js
  - node_modules\@inworld\nodejs-sdk\build\src\clients\inworld.client.js
  - node_modules\@inworld\nodejs-sdk\build\src\index.js
  at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
  at Module._resolveFilename (node_modules\module-alias\index.js:49:29)
  at Module._load (node:internal/modules/cjs/loader:922:27)
  at Module.require (node:internal/modules/cjs/loader:1143:19)
  at require (node:internal/modules/cjs/helpers:119:18)
  at Object.<anonymous> (node_modules\@inworld\nodejs-sdk\build\src\entities\error.entity.js:5:35)
  at Module._compile (node:internal/modules/cjs/loader:1256:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
  at Module.load (node:internal/modules/cjs/loader:1119:32)
  at Module._load (node:internal/modules/cjs/loader:960:12)
```

## What did you expect to happen?

No error

## Anything else we should know?
Maybe due to https://github.com/inworld-ai/inworld-nodejs-sdk/commit/425250d9eb178cc8fee6106dee5b67df08b501b8 adding `import { deserializeGrpcStatusDetails } from '@stackpath/node-grpc-error-details';` but only adding `@stackpath/node-grpc-error-details` as a development dependency?

**Comment by tshashkova** [comment]
@happy-turtle Fixed, try to use 1.14.2
