### ISSUE TITLE
Error: 14 UNAVAILABLE: No connection established

### ISSUE THREAD

**Issue by atorsvn** [inworld-ai/inworld-nodejs-sdk#30]
Suddenly started getting this error 

```
Error: 14 UNAVAILABLE: No connection established
    at callErrorFromStatus (/home/lucky/discord/sugarbelle/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/home/lucky/discord/sugarbelle/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at Object.onReceiveStatus (/home/lucky/discord/sugarbelle/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/home/lucky/discord/sugarbelle/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /home/lucky/discord/sugarbelle/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/home/lucky/discord/sugarbelle/node_modules/@grpc/grpc-js/build/src/client.js:160:34)
    at ServiceClientImpl.generateSessionToken (/home/lucky/discord/sugarbelle/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at node:internal/util:362:7
    at new Promise (<anonymous>)
    at bound  (node:internal/util:348:12)
    at TokenClientGrpcService.<anonymous> (/home/lucky/discord/sugarbelle/node_modules/@inworld/nodejs-sdk/build/src/services/gprc/token_client_grpc.service.js:36:93)
    at Generator.next (<anonymous>)
    at /home/lucky/discord/sugarbelle/node_modules/@inworld/nodejs-sdk/build/src/services/gprc/token_client_grpc.service.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/lucky/discord/sugarbelle/node_modules/@inworld/nodejs-sdk/build/src/services/gprc/token_client_grpc.service.js:4:12) {
  code: 14,
  details: 'No connection established',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}```

**Comment by RodrigoRVSN** [comment]
How to reproduce this error?
I'm not getting this error in the hello world example

**Comment by atorsvn** [comment]
Its been resolved here https://github.com/atorsvn/inworld_python
